name: Build Vue

# Controls when the action will run. 
on:
  push:
    branches: [ next ]

jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.0
      with:
        username: 'logotip4ik'
        reponame: 'my-journal'
        cname: 'journal.bogdankostyuk.xyz'
        token: ${{ secrets.GITHUB_TOKEN }}
